# Generated by Django 3.2.21 on 2023-11-21 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anticedentincident', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anticedent')),
                ('anticedent_definition', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviorincident', models.CharField(max_length=30, verbose_name='Behavior')),
                ('behavior_definition', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Behavior Definition')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='*Unique Identifier allows another to use FBO form if provided by you only', max_length=150, verbose_name='Unique Identifier')),
                ('user_student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='postts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviorfunction', models.CharField(blank=True, max_length=30, null=True, verbose_name='Function')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.student')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviorenviroment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enviroment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.student')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedCaseManagerSlug', models.CharField(blank=True, max_length=20, null=True)),
                ('assignedStudentSlug', models.CharField(blank=True, max_length=20, null=True)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviorconsequence', models.CharField(blank=True, max_length=30, null=True, verbose_name='Consequence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.student')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, verbose_name='Unique Identification')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration')),
                ('time', models.TimeField(blank=True, null=True)),
                ('frequency', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequency')),
                ('anticedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.anticedent')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.behavior')),
                ('consequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.consequence')),
                ('enviroment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.enviroment')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.function')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.student')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='behavior',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.student'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anticedent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.student'),
        ),
        migrations.AddField(
            model_name='anticedent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
