# Generated by Django 3.2.13 on 2023-08-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='consequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.consequence'),
        ),
    ]
