# Generated by Django 3.2.21 on 2024-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Occupation'),
        ),
    ]
