# Generated by Django 3.2.21 on 2023-12-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticedent',
            name='anticedent_definition',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Antecedent Definition'),
        ),
        migrations.AlterField(
            model_name='anticedent',
            name='anticedentincident',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Antecedent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(help_text='*Unique Identification allows another to use FBO form if provided by you only', max_length=150, verbose_name='Unique Identifier'),
        ),
    ]
