# Generated by Django 3.2.21 on 2024-01-27 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0002_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviroment',
            name='intensity_definition',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Define Intensity for 1(Mild), 2(Moderate), 3(Severe)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='case',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration(Sec)'),
        ),
    ]
