# Generated by Django 3.2.21 on 2023-11-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0002_alter_enviroment_behaviorenviroment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='anticedent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.anticedent', verbose_name='Antecedent'),
        ),
        migrations.AlterField(
            model_name='case',
            name='behavior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bip.behavior'),
        ),
        migrations.AlterField(
            model_name='case',
            name='enviroment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bip.enviroment', verbose_name='Setting'),
        ),
    ]
