# Generated by Django 3.2.13 on 2023-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0002_alter_case_consequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='context',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Context'),
        ),
        migrations.AddField(
            model_name='case',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequency'),
        ),
    ]
