# Generated by Django 3.2.21 on 2024-01-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0002_alter_casemanager_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='intensity',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], default=1, null=True, verbose_name='Intensity'),
        ),
    ]
