# Generated by Django 3.2.21 on 2024-01-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0003_auto_20240127_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviroment',
            name='intensity_definition',
        ),
        migrations.AddField(
            model_name='behavior',
            name='intensity_definition',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Define Intensity for 1(Mild), 2(Moderate), 3(Severe)'),
        ),
    ]
