# Generated by Django 3.2.21 on 2024-01-20 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0003_case_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='intensity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1, message='Intensity must be at least 1.'), django.core.validators.MaxValueValidator(3, message='Intensity cannot be greater than 3.')], verbose_name='Intensity'),
        ),
    ]
