# Generated by Django 3.2.21 on 2024-02-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0004_auto_20240127_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='intensity_definition',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Define Intensity for 1(Mild), 2(Moderate), 3(Severe)'),
        ),
    ]
