# Generated by Django 3.2.21 on 2023-11-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0004_student_casemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='casemanager',
        ),
    ]
