# Generated by Django 3.2.21 on 2023-11-11 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bip', '0005_remove_student_casemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanager',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='Unique Identification'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='user',
            field=models.OneToOneField(blank=True, default=5000, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
