# Generated by Django 3.2.21 on 2023-11-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bip', '0006_auto_20231111_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='user',
            field=models.OneToOneField(blank=True, default=5000, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
